
semestres:
  2026-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - Introducció mates
      - Fonaments programació
      - Gestió organitzacions
    certificacions:
      - CompTIA ITF+
  2026-S2:
    mesos: ["juliol","agost","setembre","octubre","novembre","desembre"]
    assignatures:
      - Àlgebra
      - Fonaments computadors
      - Gestió projectes
    certificacions:
      - Linux+
  2027-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - Lògica
      - Estructura de computadors
      - Treball en equip a la xarxa
    certificacions:
      - Network+
  2027-S2:
    mesos: ["juliol","agost","setembre","octubre","novembre","desembre"]
    assignatures:
      - Anàlisi matemàtica
      - Pràctiques programació
      - Enginyeria del programari
    certificacions:
      - AWS Cloud Practitioner
  2028-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - Estadística
      - Sistemes operatius
      - Fonaments físics informàtica
    certificacions:
      - Azure Fundamentals
  2028-S2:
    mesos: ["juliol","agost","setembre","octubre","novembre","desembre"]
    assignatures:
      - Grafs i complexitat
      - Disseny i programació OO aplicada
      - Admin de xarxes i SO
    certificacions:
      - AWS Solutions Architect
  2029-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - Interacció persona-ordinador
      - IA
      - Xarxes i aplicacions Internet
  2029-S2:
    mesos: ["juliol","agost","setembre","octubre","novembre","desembre"]
    assignatures:
      - Ús de bases de dades
      - Sistemes distribuïts
      - Competència comunicativa
    certificacions:
      - Associate Azure Administrator
  2030-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - Disseny de bases de dades
      - Anglès I
      - Estructura de xarxes
    certificacions:
      - LPI
      - ITIL Foundation
  2030-S2:
    mesos: ["juliol","agost","setembre","octubre","novembre","desembre"]
    assignatures:
      - Seguretat en xarxes
      - Fonaments de SI
      - Anglès II
    certificacions:
      - PMP
  2031-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - Disseny de xarxes
      - Integració de SI
      - Arquitectura de BBDD
      - Iniciativa emprenedora
    certificacions:
      - Agile PM
      - CISSP
  2031-S2:
    mesos: ["juliol","agost","setembre","octubre","novembre","desembre"]
    assignatures:
      - Integració de SI
      - Gestió funcional de serveis SI/TI
      - Ús de SI a organitzacions
      - Planificació i ús estratègic de SI
    certificacions:
      - TOGAF
  2032-S1:
    mesos: ["gener","febrer","març","abril","maig","juny"]
    assignatures:
      - TFG
    certificacions:
      - COBIT
